name: Demo
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'get tag version'
        required: true
        default: '0.0.1'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          VERSION=${{ github.event.inputs.tag }}
          if [ -z "$VERSION" ]
          then
            echo "from push"
            VERSION=${GITHUB_REF#refs/*/}
          else
            echo "workflow_dispatch"
          fi

          echo ::set-output name=version::${VERSION}

      - name: Create env file
        run: |
          cat << EOF > .env.prod
          DEMO1=123
          DEMO2=${{ secrets.DEMO2 }}
          EOF
          cat .env.prod